### ISSUE TITLE
Cut another release

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-mock-request#8]
given the frequency of updates to this thing, we might want to consider making Github Actions do this work for us.

**Comment by jaller94** [comment]
What processes do you want to set up GitHub actions for?
The release to NPM?

**Comment by turt2live** [comment]
Yea, although looking around it seems like we don't have the beta enabled. When I was playing with it on a personal project it looked promising: https://developer.github.com/actions/

**Comment by jaller94** [comment]
You might be able to sign up for it here:
https://github.com/features/actions

And here is a starting place for NPM deploys:
https://github.com/actions/npm

(Disclosure: I don’t have any experiences with GitHub Actions, but I want to learn about them.)

**Comment by jaller94** [comment]
As we are talking about pushing on NPM, it’s important to store secrets in a safe place.
https://developer.github.com/actions/creating-workflows/storing-secrets/

Everyone with write access to the repository will be able to access secrets for GitHub Actions.
The actions itself are stored publicly in the repo, so everyone can fork and suggest adaptions. The beta "just" gives the permission to execute them on your repos and edit them in a visual editor.

**Comment by jaller94** [comment]
Secrets get configured here:
https://github.com/matrix-org/matrix-mock-request/settings/secrets

That would include a secret like `NPM_AUTH_TOKEN` which becomes available as a ENV variable for the actions.

I am currently experimenting here:
https://github.com/jaller94/matrix-mock-request/pull/1

**Comment by jaller94** [comment]
How comfortable are you with blind releases without unit tests?
I file #9 to raise awareness that the implementation of GitHub Actions for releases might lead to the publishing of broken versions.

I wonder at what point the work of maintaining this becomes more effort than manually releasing new versions, because this is just a mock library to support the actual libraries. Then again, tests and some automation would be beneficial for the confidence of new releases either way.

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/55106228-06bde180-5094-11e9-90a1-00063084d2b3.png)

This happened 🎉

**Comment by jryans** [comment]
Ah, I thought we had already released your change... 😅 Anyway, I updated the 1.2.3 changelog to mention it as well.
